### ISSUE TITLE
edup总张数识别问题

### ISSUE THREAD

**Issue by abcmaosi** [yumenaka/comigo#40]
如题，翻页模式网页显示总张数337页，可漫画在167页就已经结束了，后面都是黑屏，所有edup漫画均有出现这个情况，如下图
![Screenshot_20240826_001851](https://github.com/user-attachments/assets/03dc58ab-fa56-4d86-bd14-b2535ee1b5a5)
但zip漫画就不会出现这个情况，如下图
![Screenshot_20240826_001830](https://github.com/user-attachments/assets/e2d9ab03-55bb-411b-abb4-03e69579a081)
服务端为ubuntu 22.04.4 LTS，客户端为Dibian12+火狐115.12.0esr
windows端问题更严重，同一漫画在chrome下只能显示24页就结束了，应该可以确定就是识别有问题了

**Comment by yumenaka** [comment]
是未完成的实验性功能（插入html），意外干扰了Epub文件，已发版修复。
https://github.com/yumenaka/comigo/releases/tag/v0.9.11

**Comment by abcmaosi** [comment]
辛苦了
